apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: chat-app

spec:
  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
      - name: chatapp-frontend
        image: deepakydv0/chatapp-frontend
        ports:
        - containerPort: 80
        env:
        - name: NODE_ENV
          value: "production"
        
